* A chip8 emulator (interpreter) written in zig
** Usage
Build using =zig build -Drelease-fast= or without release fast, than run =./zig-out/bin/emu <PATH TO ROM>=

** TODOS
- [ ] Debugging
- [ ] The emulator is too fast? The screen flickers? Maybe use Texture instead of rectangles?
- [X] Sound
- [X] All opcodes working
  
** Games working
- [X] Pong
- [X] Tetris
- [X] Cave
- [X] Tank

*** Pong
Press 1 and Q to move p1 and 4 and R to move p2.

*** Tetris
Press W to move left, E to move right, Q to rotate, S to move down faster

*** Cave
You have to get to the exit without crashing.
Press 2 to go up, Q to go left, E to go right and S to go down

*** Tank
Destroy the enemy, press W to shoot, Q to move left, E to move right, 2 to move down and S to move up

** Packages used
- [[https://github.com/Hejsil/zig-clap][zig-clap]]
- [[https://github.com/MasterQ32/SDL.zig][SDL.zig]]

** The roms were taken from
- test-opcode.ch8 [[https://github.com/corax89/chip8-test-rom]]
- BC_test.ch8, CAVE, Maze, PONG, TANK, TETRIS [[https://github.com/cj1128/chip8-emulator/tree/master/rom]]
- Chipquarium, Heart monitor, morse code [[https://github.com/mattmikolay/chip-8]]
