* A chip8 emulator (interpreter) written in zig
** Usage
Build using =zig build -Drelease-fast= or without release fast, than run =./zig-out/bin/emu <PATH TO ROM>=

** TODOS
- [ ] Notcurses input. I have no Idea on how to do it, I can't use sdl because I need a window for input in sdl
# - [ ] The emulator is too fast? The screen flickers? Is it supposed to do that?
- [ ] Add some Images or gifs to showcase the project
- [X] Sound
- [X] All opcodes working
  
** Roms
*** Pong
Press 1 and Q to move p1 and 4 and R to move p2.

*** Tetris
Press W to move left, E to move right, Q to rotate, S to move down faster

*** Cave
You have to get to the exit without crashing.
Press 2 to go up, Q to go left, E to go right and S to go down

*** Tank
Destroy the enemy, press W to shoot, Q to move left, E to move right, 2 to move down and S to move up

** Dependencies
- [[https://ziglang.org/][zig]]
- [[https://github.com/Hejsil/zig-clap][zig-clap]]
- [[https://github.com/MasterQ32/SDL.zig][SDL.zig]]
- [[https://www.libsdl.org/index.php][SDL]]
- [[https://github.com/dankamongmen/notcurses][notcurses]]

** The roms were taken from
- test-opcode.ch8 [[https://github.com/corax89/chip8-test-rom]]
- BC_test.ch8, CAVE, Maze, PONG, TANK, TETRIS [[https://github.com/cj1128/chip8-emulator/tree/master/rom]]
- Chipquarium, Heart monitor, morse code [[https://github.com/mattmikolay/chip-8]]

** Roadmap
- [ ] Add debugging functionality
- [ ] Add support for latest chip8 standards
- [ ] Target Web
- [ ] Target Android

** Some notes on the repo
- Why do this? Just for fun
- Why are there so many sdl directories? This is because:
  1) I don't know how to organize it better.
  2) The sdl folders in src/ are not needed but are useful to get lsp when writing, it would be hell for me to write without it, when I finish development I will eventually delete them and leave only the folder in the root directory
- The idea is to make chip.zig one file, but I wouldn't know how to import in the two projects since I can't do @import("../chip.zig"), the same applies to clap. I will change it when I discover how to do that
- Should I leave the roms tested in the repo? I don't know
